[package]
name = "dsgvo-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-native-tls", "json", "chrono"] }
reqwest = { version = "0.12.14", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4.40", features = ["serde"] }
log = "0.4.26"
env_logger = "0.11.7"
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["suggestions"] }

[profile.release]
lto = true
panic = "abort"
debug = "none"
