[package]
name = "dsgvo-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-native-tls", "json", "chrono"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
chrono = { version = "0.4.39", features = ["serde"] }
log = "0.4.25"
env_logger = "0.11.6"
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["suggestions"] }

[profile.release]
lto = true
panic = "abort"
debug = "none"
